// src/components/ArmSlider.tsx
import { Shield } from "lucide-react";
import { cn } from "../lib/utils";

type ArmSliderProps = {
  connected: boolean;
  armed: boolean;
  onArm: (force: boolean) => void;
  onDisarm: (force: boolean) => void;
  replayActive?: boolean;
};

export function ArmSlider({ connected, armed, onArm, onDisarm, replayActive }: ArmSliderProps) {
  const disabled = !connected || !!replayActive;
  return (
    <div className={cn("rounded-lg border border-border bg-bg-primary p-3", disabled && "opacity-50")}>
      <div className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-text-muted">
        <Shield className="h-3.5 w-3.5" />
        {armed ? "Armed" : "Disarmed"}
      </div>

      <div className="relative flex h-11 select-none rounded-full bg-bg-tertiary p-1">
        {/* Sliding background pill */}
        <div
          className={cn(
            "absolute inset-y-1 w-[calc(50%-4px)] rounded-full transition-all duration-200 ease-out",
            armed ? "left-[calc(50%+2px)] bg-danger/20" : "left-1 bg-bg-secondary"
          )}
        />

        <button
          type="button"
          disabled={disabled || !armed}
          onClick={() => onDisarm(false)}
          className={cn(
            "relative z-10 flex flex-1 items-center justify-center rounded-full text-sm font-medium transition-colors",
            armed
              ? "text-text-secondary active:text-text-primary"
              : "text-text-primary"
          )}
        >
          Disarm
        </button>

        <button
          type="button"
          disabled={disabled || armed}
          onClick={() => onArm(false)}
          className={cn(
            "relative z-10 flex flex-1 items-center justify-center rounded-full text-sm font-medium transition-colors",
            armed
              ? "text-danger"
              : "text-text-secondary active:text-text-primary"
          )}
        >
          Arm
        </button>
      </div>
    </div>
  );
}

// src/components/flight/ArmSlider.svelte
<script lang="ts">
  import { Shield } from "lucide-svelte";
  import { fromStore } from "svelte/store";

  import { getSessionViewStoreContext } from "../../app/shell/runtime-context";
  import { REPLAY_READONLY_COPY, REPLAY_READONLY_TITLE, isReplayReadonly } from "../../lib/replay-readonly";
  import { armVehicle, disarmVehicle } from "../../telemetry";

  const sessionView = fromStore(getSessionViewStoreContext());

  let view = $derived(sessionView.current);
  let connected = $derived(view.connected);
  let vehicleState = $derived(view.vehicleStatusCard);
  let armed = $derived(vehicleState.armStateText === "ARMED");
  let replayReadonly = $derived(isReplayReadonly(view.activeSource));
  let locked = $derived(!connected || replayReadonly);

  let busy = $state(false);
  let commandError = $state<string | null>(null);

  async function handleArm() {
    if (armed || locked) return;
    busy = true;
    commandError = null;
    try {
      await armVehicle(false);
    } catch (error) {
      commandError = error instanceof Error ? error.message : String(error);
    } finally {
      busy = false;
    }
  }

  async function handleDisarm() {
    if (!armed || locked) return;
    busy = true;
    commandError = null;
    try {
      await disarmVehicle(false);
    } catch (error) {
      commandError = error instanceof Error ? error.message : String(error);
    } finally {
      busy = false;
    }
  }
</script>

<div class="rounded-lg border border-border bg-bg-primary p-3" class:opacity-50={locked}>
  {#if replayReadonly}
    <div class="mb-3 rounded-lg border border-warning/40 bg-warning/10 px-3 py-3 text-sm text-warning" data-testid="arm-replay-readonly-banner">
      <p class="font-semibold">{REPLAY_READONLY_TITLE}</p>
      <p class="mt-1">{REPLAY_READONLY_COPY}</p>
    </div>
  {/if}

  {#if commandError}
    <div class="mb-3 rounded-lg border border-danger/40 bg-danger/10 px-3 py-3 text-sm text-danger">{commandError}</div>
  {/if}

  <div class="flex items-center gap-2">
    <Shield aria-hidden="true" class="text-text-muted" size={14} />
    <p class="text-xs font-semibold uppercase tracking-wider text-text-muted">
      {armed ? "Armed" : "Disarmed"}
    </p>
  </div>

  <div class="mt-2" class:opacity-50={locked || busy} class:pointer-events-none={locked || busy}>
    <div class="relative flex h-9 rounded-full bg-bg-tertiary p-[3px]">
      <div
        class={[
          "absolute top-[3px] h-[calc(100%_-_6px)] w-[calc(50%_-_3px)] rounded-full transition-[left,background] duration-200 ease-in-out",
          armed ? "left-1/2 bg-danger/45" : "left-[3px] bg-bg-secondary",
        ]}
      ></div>
      <button
        class={[
          "relative z-[1] flex-1 rounded-full border-none bg-transparent text-xs font-semibold text-text-muted transition-colors duration-150 disabled:cursor-default",
          !armed && "text-text-primary",
        ]}
        disabled={!armed || locked || busy}
        onclick={handleDisarm}
        type="button"
      >
        Disarm
      </button>
      <button
        class={[
          "relative z-[1] flex-1 rounded-full border-none bg-transparent text-xs font-semibold text-text-muted transition-colors duration-150 disabled:cursor-default",
          armed && "text-text-primary",
        ]}
        disabled={armed || locked || busy}
        onclick={handleArm}
        type="button"
      >
        Arm
      </button>
    </div>
  </div>
</div>
