// src/components/mission/MissionInspector.tsx
import { useState, useCallback, useMemo } from "react";
import { Settings2 } from "lucide-react";
import {
    commandDisplayName,
    commandPosition,
    commandCategory,
    defaultCommand,
    geoPoint3dLatLon,
    withCommandField,
} from "../../lib/mavkit-types";
import type {
    MissionItem,
    MissionCommand,
    GeoPoint3d,
    HomePosition,
    RawMissionCommand,
} from "../../lib/mavkit-types";
import {
    rawFallbackParams,
    resolveCommandMetadata,
    variantToCommandId,
    type ParamSlot,
} from "../../lib/mission-command-metadata";
import { CommandPicker } from "./CommandPicker";
import { MissionCommandHelp } from "./MissionCommandHelp";
import { cn } from "../../lib/utils";
import type { TypedDraftItem } from "../../lib/mission-draft-typed";
import {
    CoordinateFields,
    AltitudeField,
    COORDINATE_MODES,
    type CoordinateMode,
} from "./coordinate-inputs";

type MissionInspectorProps = {
    missionType: "mission" | "fence" | "rally";
    draftItem: TypedDraftItem;
    index: number;
    previousItem: TypedDraftItem | null;
    homePosition: HomePosition | null;
    readOnly?: boolean;
    isSelected: boolean;
    onUpdateCommand?: (index: number, command: MissionCommand) => void;
    onUpdateAltitude: (index: number, altitudeM: number) => void;
    onUpdateCoordinate: (index: number, field: "latitude_deg" | "longitude_deg", valueDeg: number) => void;
    onSelect: (index: number) => void;
};

// ---------------------------------------------------------------------------
// Typed field extraction
// ---------------------------------------------------------------------------

type EditableField = {
    key: string;
    label: string;
    type: "number" | "boolean" | "enum";
    value: number | boolean | string;
    enumOptions?: { value: string; label: string }[];
    units?: string;
    required?: boolean;
    supported?: boolean;
    description?: string;
    /** Offset added for display and subtracted on commit (e.g. +1 for 0-based indices). */
    displayOffset?: number;
};

type CommandVariantInfo = {
    category: "Nav" | "Do" | "Condition";
    variant: string;
};

/** Fields that are 0-based item indices internally but shown 1-based in the UI. */
const ONE_INDEXED_FIELDS = new Set(["target_index"]);

function commandVariantName(cmd: MissionCommand): CommandVariantInfo | null {
    if ("Nav" in cmd) {
        const nav = cmd.Nav;
        return {
            category: "Nav",
            variant: typeof nav === "string" ? nav : Object.keys(nav)[0],
        };
    }

    if ("Do" in cmd) {
        const d = cmd.Do;
        return {
            category: "Do",
            variant: typeof d === "string" ? d : Object.keys(d)[0],
        };
    }

    if ("Condition" in cmd) {
        const c = cmd.Condition;
        return {
            category: "Condition",
            variant: typeof c === "string" ? c : Object.keys(c)[0],
        };
    }

    return null;
}

function commandVariantData(cmd: MissionCommand): Record<string, unknown> | null {
    if ("Nav" in cmd) {
        const nav = cmd.Nav;
        if (typeof nav === "string") return null;
        const variant = Object.keys(nav)[0];
        return (nav as Record<string, Record<string, unknown>>)[variant] ?? null;
    }

    if ("Do" in cmd) {
        const d = cmd.Do;
        if (typeof d === "string") return null;
        const variant = Object.keys(d)[0];
        return (d as Record<string, Record<string, unknown>>)[variant] ?? null;
    }

    if ("Condition" in cmd) {
        const c = cmd.Condition;
        if (typeof c === "string") return null;
        const variant = Object.keys(c)[0];
        return (c as Record<string, Record<string, unknown>>)[variant] ?? null;
    }

    return null;
}

function rawCommandData(cmd: MissionCommand): RawMissionCommand | null {
    if ("Other" in cmd) {
        return cmd.Other;
    }

    return null;
}

function resolveInspectorMetadata(cmd: MissionCommand) {
    const raw = rawCommandData(cmd);
    if (raw) {
        return rawFallbackParams(raw.command);
    }

    const variantInfo = commandVariantName(cmd);
    if (!variantInfo) return null;

    const commandId = variantToCommandId(variantInfo.category, variantInfo.variant);
    if (commandId === undefined) return null;

    return resolveCommandMetadata(commandId);
}

function normalizeEnumOptions(
    value: string,
    enumOptions?: { value: string; label: string }[],
): { value: string; label: string }[] {
    if (!enumOptions || enumOptions.length === 0) {
        return [{ value, label: fieldLabel(value) }];
    }

    if (enumOptions.some((option) => option.value === value)) {
        return enumOptions;
    }

    return [...enumOptions, { value, label: fieldLabel(value) }];
}

const RAW_FIELD_ORDER: ParamSlot[] = ["param1", "param2", "param3", "param4", "x", "y", "z"];

function withUpdatedCommandField(cmd: MissionCommand, fieldKey: string, value: unknown): MissionCommand {
    const raw = rawCommandData(cmd);
    if (raw && fieldKey in raw) {
        return {
            Other: {
                ...raw,
                [fieldKey]: typeof value === "number" ? value : Number(value),
            },
        };
    }

    return withCommandField(cmd, fieldKey, value);
}

function extractRawFields(cmd: MissionCommand): EditableField[] {
    const raw = rawCommandData(cmd);
    if (!raw) return [];

    const metadata = rawFallbackParams(raw.command);

    return RAW_FIELD_ORDER.map((fieldKey) => {
        const descriptor = metadata.params[fieldKey];
        return {
            key: fieldKey,
            label: descriptor?.label ?? fieldLabel(fieldKey),
            type: "number",
            value: raw[fieldKey],
            units: descriptor?.units,
            required: descriptor?.required,
            supported: descriptor?.supported ?? true,
            description: descriptor?.description,
        } satisfies EditableField;
    });
}

/** Extract editable fields from the inner variant of a MissionCommand using rich metadata. */
function extractMetadataFields(cmd: MissionCommand): EditableField[] {
    const raw = rawCommandData(cmd);
    if (raw) {
        return extractRawFields(cmd);
    }

    const inner = commandVariantData(cmd);
    if (!inner) return [];

    const metadata = resolveInspectorMetadata(cmd);
    const typedFields = metadata?.typedFields ?? {};
    const fields: EditableField[] = [];

    for (const [key, val] of Object.entries(inner)) {
        if (key === "position") continue;

        const descriptor = typedFields[key];
        if (descriptor?.hidden) continue;

        const common = {
            key,
            label: descriptor?.label ?? fieldLabel(key),
            units: descriptor?.units,
            required: descriptor?.required,
            supported: descriptor?.supported ?? true,
            description: descriptor?.description,
            displayOffset: ONE_INDEXED_FIELDS.has(key) ? 1 : undefined,
        } satisfies Omit<EditableField, "type" | "value" | "enumOptions">;

        if (typeof val === "number") {
            fields.push({
                ...common,
                type: "number",
                value: val,
            });
            continue;
        }

        if (typeof val === "boolean") {
            fields.push({
                ...common,
                type: "boolean",
                value: val,
            });
            continue;
        }

        if (typeof val === "string") {
            fields.push({
                ...common,
                type: "enum",
                value: val,
                enumOptions: normalizeEnumOptions(val, descriptor?.enumValues),
            });
        }
    }

    return fields;
}

function fieldLabel(key: string): string {
    return key
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Position extraction helpers
// ---------------------------------------------------------------------------

function positionFromDraftItem(
    item: TypedDraftItem,
): GeoPoint3d | null {
    const doc = item.document;
    // MissionItem has a command field
    if ("command" in doc) {
        return commandPosition((doc as MissionItem).command);
    }
    // GeoPoint3d variants
    if ("Msl" in doc || "RelHome" in doc || "Terrain" in doc) {
        return doc as GeoPoint3d;
    }
    // FenceRegion — no position
    return null;
}

function previousPosition(
    previousItem: TypedDraftItem | null,
): { latitude_deg: number; longitude_deg: number } | null {
    if (!previousItem) return null;
    const pos = positionFromDraftItem(previousItem);
    if (!pos) return null;
    return geoPoint3dLatLon(pos);
}

function EditableCommandFields({
    fields,
    command,
    disabled,
    onUpdateCommand,
}: {
    fields: EditableField[];
    command: MissionCommand;
    disabled: boolean;
    onUpdateCommand: (cmd: MissionCommand) => void;
}) {
    if (fields.length === 0) return null;

    return (
        <div className="space-y-1.5">
            <span className="text-[10px] font-medium text-text-muted">Parameters</span>
            {fields.map((f) => {
                const fieldDisabled = disabled || f.supported === false;

                return (
                    <div
                        key={f.key}
                        data-command-field={f.key}
                        data-supported={f.supported === false ? "false" : "true"}
                        data-required={f.required ? "true" : "false"}
                        className={cn("space-y-0.5", f.supported === false && "opacity-60")}
                    >
                        <label
                            className="flex items-center gap-1 text-[10px] text-text-muted"
                            title={f.description}
                        >
                            <span>{f.label}</span>
                            {f.required && (
                                <span className="text-warning" aria-label="required">
                                    *
                                </span>
                            )}
                            {f.required && (
                                <span className="text-[9px] text-warning/80">required</span>
                            )}
                        </label>

                        {f.type === "number" && (
                            <div className="relative">
                                <NumberFieldInput
                                    fieldKey={f.key}
                                    value={f.value as number}
                                    command={command}
                                    disabled={fieldDisabled}
                                    onUpdateCommand={onUpdateCommand}
                                    displayOffset={f.displayOffset}
                                    ariaLabel={f.label}
                                    className={f.units ? "pr-12" : undefined}
                                />
                                {f.units && (
                                    <span
                                        data-command-field-unit={f.key}
                                        className="pointer-events-none absolute inset-y-0 right-2 flex items-center text-[10px] text-text-muted/70"
                                    >
                                        {f.units}
                                    </span>
                                )}
                            </div>
                        )}

                        {f.type === "boolean" && (
                            <button
                                type="button"
                                aria-label={f.label}
                                disabled={fieldDisabled}
                                title={f.description}
                                onClick={() => onUpdateCommand(withUpdatedCommandField(command, f.key, !(f.value as boolean)))}
                                className={cn(
                                    "rounded border px-1.5 py-1 text-xs",
                                    f.value
                                        ? "border-accent/40 bg-accent/10 text-accent"
                                        : "border-border bg-bg-input text-text-muted",
                                    fieldDisabled && "cursor-not-allowed opacity-50",
                                )}
                            >
                                {f.value ? "Yes" : "No"}
                            </button>
                        )}

                        {f.type === "enum" && (
                            <select
                                aria-label={f.label}
                                disabled={fieldDisabled}
                                title={f.description}
                                value={f.value as string}
                                onChange={(e) => onUpdateCommand(withUpdatedCommandField(command, f.key, e.target.value))}
                                className={cn(
                                    "w-full rounded border border-border bg-bg-input px-1.5 py-1 text-xs text-text-primary",
                                    fieldDisabled && "cursor-not-allowed opacity-70",
                                )}
                            >
                                {f.enumOptions?.map((opt) => (
                                    <option key={opt.value} value={opt.value}>
                                        {opt.label}
                                    </option>
                                ))}
                            </select>
                        )}

                        {f.supported === false && (
                            <p data-command-field-note={f.key} className="text-[9px] text-warning/80">
                                {f.description ?? "Not supported by ArduPilot for this command."}
                            </p>
                        )}
                    </div>
                );
            })}
        </div>
    );
}

/** Number input that commits on blur or Enter, avoiding per-keystroke updates. */
function NumberFieldInput({
    fieldKey,
    value,
    command,
    disabled,
    onUpdateCommand,
    displayOffset = 0,
    ariaLabel,
    className,
}: {
    fieldKey: string;
    value: number;
    command: MissionCommand;
    disabled: boolean;
    onUpdateCommand: (cmd: MissionCommand) => void;
    /** Offset added for display and subtracted on commit (e.g. 1 for 0→1 based indices). */
    displayOffset?: number;
    ariaLabel?: string;
    className?: string;
}) {
    const shown = value + displayOffset;
    const [draft, setDraft] = useState(String(shown));
    const [focused, setFocused] = useState(false);

    const displayValue = focused ? draft : String(shown);

    const commit = useCallback(() => {
        const parsed = parseFloat(draft);
        if (!Number.isNaN(parsed) && parsed !== shown) {
            onUpdateCommand(withUpdatedCommandField(command, fieldKey, parsed - displayOffset));
        } else {
            setDraft(String(shown));
        }
    }, [draft, shown, command, fieldKey, displayOffset, onUpdateCommand]);

    return (
        <input
            type="text"
            inputMode="decimal"
            aria-label={ariaLabel}
            disabled={disabled}
            value={displayValue}
            onChange={(e) => setDraft(e.target.value)}
            onFocus={() => { setDraft(String(shown)); setFocused(true); }}
            onBlur={() => { setFocused(false); commit(); }}
            onKeyDown={(e) => { if (e.key === "Enter") { e.currentTarget.blur(); } }}
            className={cn(
                "w-full rounded border border-border bg-bg-input px-1.5 py-1 text-xs tabular-nums text-text-primary",
                className,
            )}
        />
    );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function MissionInspector({
    missionType,
    draftItem,
    index,
    previousItem,
    homePosition,
    readOnly = false,
    isSelected,
    onUpdateCommand,
    onUpdateAltitude,
    onUpdateCoordinate,
    onSelect,
}: MissionInspectorProps) {
    const controlReadOnly = readOnly || draftItem.readOnly;
    const [coordMode, setCoordMode] = useState<CoordinateMode>("absolute");

    const position = useMemo(() => positionFromDraftItem(draftItem), [draftItem]);
    const prevPos = useMemo(() => previousPosition(previousItem), [previousItem]);

    const isMissionItem = "command" in draftItem.document;
    const missionItem = isMissionItem ? (draftItem.document as MissionItem) : null;
    const category = missionItem ? commandCategory(missionItem.command) : null;
    const displayName = missionItem
        ? commandDisplayName(missionItem.command)
        : missionType === "fence"
            ? "Fence Region"
            : "Rally Point";

    const editableFields = useMemo(
        () => (missionItem ? extractMetadataFields(missionItem.command) : []),
        [missionItem],
    );

    const currentCommandMetadata = useMemo(
        () => (missionItem ? resolveInspectorMetadata(missionItem.command) : null),
        [missionItem],
    );

    const showCoordinateInputs = Boolean(
        position && !(currentCommandMetadata?.params.x?.hidden || currentCommandMetadata?.params.y?.hidden),
    );

    const ensureSelected = useCallback(() => {
        if (!isSelected) {
            onSelect(index);
        }
    }, [index, isSelected, onSelect]);

    const handleCoordCommit = useCallback(
        (field: "latitude_deg" | "longitude_deg", valueDeg: number) => {
            onUpdateCoordinate(index, field, valueDeg);
        },
        [index, onUpdateCoordinate],
    );

    return (
        <div
            data-mission-inspector
            data-mission-coordinate-mode={coordMode}
            className="space-y-2.5 rounded-lg border border-border bg-bg-secondary p-3"
        >
            <div className="flex items-center gap-2">
                <Settings2 className="h-3.5 w-3.5 text-accent" />
                <span className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">
                    Inspector
                </span>
                <span className="ml-auto text-[10px] tabular-nums text-text-muted">
                    #{index + 1}
                </span>
            </div>

            <div className="space-y-0.5">
                <label className="text-[10px] text-text-muted">Command</label>
                {isMissionItem && !controlReadOnly && onUpdateCommand ? (
                    <CommandPicker
                        currentName={displayName}
                        onSelect={(cat, variant) => {
                            const newCmd = defaultCommand(cat, variant, position ?? undefined);
                            onUpdateCommand(index, newCmd);
                        }}
                    />
                ) : (
                    <div className="rounded border border-border bg-bg-input px-1.5 py-1 text-xs text-text-primary">
                        {displayName}
                        {category && (
                            <span className="ml-1.5 text-[9px] uppercase text-text-muted/60">
                                {category}
                            </span>
                        )}
                    </div>
                )}
            </div>

            {currentCommandMetadata && (
                <MissionCommandHelp metadata={currentCommandMetadata} />
            )}

            {draftItem.readOnly && (
                <p className="rounded border border-warning/30 bg-warning/5 px-2 py-1 text-[10px] text-warning/80">
                    Raw/unsupported item preserved read-only.
                </p>
            )}

            {missionItem && onUpdateCommand && (
                <EditableCommandFields
                    fields={editableFields}
                    command={missionItem.command}
                    disabled={controlReadOnly}
                    onUpdateCommand={(cmd) => onUpdateCommand(index, cmd)}
                />
            )}

            {position && (
                <>
                    {showCoordinateInputs && (
                        <>
                            <div className="flex items-center gap-1.5 border-t border-border/50 pt-2">
                                <span className="text-[10px] font-medium text-text-muted">Coordinates</span>
                                <div className="ml-auto flex rounded border border-border text-[9px]">
                                    {COORDINATE_MODES.map((m) => (
                                        <button
                                            key={m.value}
                                            data-mission-coordinate-mode={m.value}
                                            aria-pressed={coordMode === m.value}
                                            onClick={() => setCoordMode(m.value)}
                                            className={cn(
                                                "px-1.5 py-0.5 transition-colors",
                                                coordMode === m.value
                                                    ? "bg-accent/20 text-accent"
                                                    : "text-text-muted hover:text-text-secondary",
                                            )}
                                        >
                                            {m.label}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <CoordinateFields
                                position={position}
                                mode={coordMode}
                                homePosition={homePosition}
                                prevPos={prevPos}
                                onCommitCoordinate={handleCoordCommit}
                                onFocusCapture={ensureSelected}
                                disabled={controlReadOnly}
                            />
                        </>
                    )}

                    <div className={cn(showCoordinateInputs ? "" : "border-t border-border/50 pt-2")}>
                        <AltitudeField
                            position={position}
                            index={index}
                            onUpdateAltitude={onUpdateAltitude}
                            onFocusCapture={ensureSelected}
                            disabled={controlReadOnly}
                        />
                    </div>
                </>
            )}
        </div>
    );
}

// src/features/mission/components/MissionInspector.svelte
<script lang="ts">
import { AlertTriangle, Info, Settings2 } from "lucide-svelte";
import type { HomePosition } from "../../../mission";
import {
  commandPosition,
  defaultCommand,
  geoPoint3dLatLon,
  withCommandField,
  type MissionCommand,
  type MissionItem,
} from "../../../lib/mavkit-types";
import {
  rawFallbackParams,
  resolveCommandMetadata,
  variantToCommandId,
  type CommandMetadata,
  type ParamSlot,
  type TypedFieldDescriptor,
} from "../../../lib/mission-command-metadata";
import type { TypedDraftItem } from "../../../lib/mission-draft-typed";
import type { SurveyRegion } from "../../../lib/survey-region";
import type { MissionPlannerSelection } from "../../../lib/stores/mission-planner";
import type { MissionPlannerSurveyPromptView } from "../../../lib/stores/mission-planner-view";
import MissionCommandPicker from "./MissionCommandPicker.svelte";
import MissionSurveyInspector from "./MissionSurveyInspector.svelte";
import { Alert, Badge, Card, EmptyState, ExternalLink, Eyebrow, FactTile, Field, HelperText, IconButton, NativeSelect, NumberInput, Switch, Tooltip } from "../../../components/ui";
import { missionWorkspaceTestIds } from "../mission-workspace-test-ids";

type EditableField = {
  key: string;
  label: string;
  type: "number" | "boolean" | "enum";
  value: number | boolean | string;
  units?: string;
  description?: string;
  required?: boolean;
  supported?: boolean;
  enumOptions?: { value: string; label: string }[];
  displayOffset?: number;
};

type Props = {
  selection: MissionPlannerSelection;
  item: TypedDraftItem | null;
  previousItem: TypedDraftItem | null;
  home: HomePosition | null;
  cruiseSpeed: number;
  selectedSurveyRegion: SurveyRegion | null;
  surveyPrompt: MissionPlannerSurveyPromptView | null;
  onUpdateCommand: (index: number, command: MissionCommand) => void;
  onUpdateLatitude: (index: number, latitudeDeg: number) => void;
  onUpdateLongitude: (index: number, longitudeDeg: number) => void;
  onUpdateAltitude: (index: number, altitudeM: number) => void;
  onUpdateSurveyRegion: (regionId: string, updater: (region: SurveyRegion) => SurveyRegion) => void;
  onGenerateSurveyRegion: (regionId: string) => Promise<unknown> | unknown;
  onPromptDissolveSurveyRegion: (regionId: string) => void;
  onDeleteSurveyRegion: (regionId: string) => void;
  onConfirmSurveyPrompt: () => Promise<unknown> | unknown;
  onDismissSurveyPrompt: () => void;
  onMarkSurveyRegionItemAsEdited: (regionId: string, localIndex: number, editedItem: MissionItem) => void;
};

const RAW_FIELD_ORDER: ParamSlot[] = ["param1", "param2", "param3", "param4", "x", "y", "z"];
const ONE_INDEXED_FIELDS = new Set(["target_index"]);

let {
  selection,
  item,
  previousItem,
  home,
  cruiseSpeed,
  selectedSurveyRegion,
  surveyPrompt,
  onUpdateCommand,
  onUpdateLatitude,
  onUpdateLongitude,
  onUpdateAltitude,
  onUpdateSurveyRegion,
  onGenerateSurveyRegion,
  onPromptDissolveSurveyRegion,
  onDeleteSurveyRegion,
  onConfirmSurveyPrompt,
  onDismissSurveyPrompt,
  onMarkSurveyRegionItemAsEdited,
}: Props = $props();

let expandedFieldKey = $state<string | null>(null);

function titleCase(value: string) {
  return value
    .replace(/_/g, " ")
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function commandVariant(command: MissionCommand): { category: "Nav" | "Do" | "Condition"; variant: string } | null {
  if ("Nav" in command) {
    return {
      category: "Nav",
      variant: typeof command.Nav === "string" ? command.Nav : Object.keys(command.Nav)[0] ?? "Waypoint",
    };
  }

  if ("Do" in command) {
    return {
      category: "Do",
      variant: typeof command.Do === "string" ? command.Do : Object.keys(command.Do)[0] ?? "Jump",
    };
  }

  if ("Condition" in command) {
    return {
      category: "Condition",
      variant: Object.keys(command.Condition)[0] ?? "Delay",
    };
  }

  return null;
}

function commandPayload(command: MissionCommand): Record<string, unknown> | null {
  if ("Nav" in command) {
    const variant = commandVariant(command);
    if (!variant) {
      return null;
    }

    if (typeof command.Nav === "string") {
      return null;
    }
    return (command.Nav as Record<string, Record<string, unknown>>)[variant.variant] ?? null;
  }

  if ("Do" in command) {
    const variant = commandVariant(command);
    if (!variant) {
      return null;
    }

    if (typeof command.Do === "string") {
      return null;
    }
    return (command.Do as Record<string, Record<string, unknown>>)[variant.variant] ?? null;
  }

  if (!("Condition" in command)) {
    return null;
  }

  const variant = commandVariant(command);
  if (!variant) {
    return null;
  }

  return (command.Condition as Record<string, Record<string, unknown>>)[variant.variant] ?? null;
}

function commandSelectValue(command: MissionCommand): string {
  const variant = commandVariant(command);
  return variant ? `${variant.category}:${variant.variant}` : "";
}

function commandMetadata(command: MissionCommand): CommandMetadata | null {
  if ("Other" in command) {
    return rawFallbackParams(command.Other.command);
  }

  const variant = commandVariant(command);
  if (!variant) {
    return null;
  }

  const commandId = variantToCommandId(variant.category, variant.variant);
  return commandId === undefined ? null : resolveCommandMetadata(commandId);
}

function typedDescriptor(command: MissionCommand, fieldKey: string): TypedFieldDescriptor | undefined {
  if ("Other" in command) {
    return undefined;
  }

  const variant = commandVariant(command);
  if (!variant) {
    return undefined;
  }

  const commandId = variantToCommandId(variant.category, variant.variant);
  if (commandId === undefined) {
    return undefined;
  }

  return resolveCommandMetadata(commandId).typedFields?.[fieldKey];
}

function rawFields(command: MissionCommand) {
  if (!("Other" in command)) {
    return [] as EditableField[];
  }

  const metadata = rawFallbackParams(command.Other.command);
  return RAW_FIELD_ORDER.map((slot) => ({
    key: slot,
    label: metadata.params[slot]?.label ?? titleCase(slot),
    type: "number" as const,
    value: command.Other[slot],
    units: metadata.params[slot]?.units,
    description: metadata.params[slot]?.description,
    required: metadata.params[slot]?.required,
    supported: metadata.params[slot]?.supported ?? true,
  }));
}

function editableFields(command: MissionCommand): EditableField[] {
  if ("Other" in command) {
    return rawFields(command);
  }

  const payload = commandPayload(command);
  if (!payload) {
    return [];
  }

  return Object.entries(payload)
    .filter(([fieldKey]) => fieldKey !== "position")
    .flatMap<EditableField>(([fieldKey, value]) => {
      const descriptor = typedDescriptor(command, fieldKey);
      if (descriptor?.hidden) {
        return [];
      }

      const common = {
        key: fieldKey,
        label: descriptor?.label ?? titleCase(fieldKey),
        units: descriptor?.units,
        description: descriptor?.description,
        required: descriptor?.required,
        supported: descriptor?.supported ?? true,
        displayOffset: ONE_INDEXED_FIELDS.has(fieldKey) ? 1 : undefined,
      };

      if (typeof value === "number") {
        return [{ ...common, type: "number" as const, value }];
      }

      if (typeof value === "boolean") {
        return [{ ...common, type: "boolean" as const, value }];
      }

      if (typeof value === "string") {
        return [{
          ...common,
          type: "enum" as const,
          value,
          enumOptions: descriptor?.enumValues ?? [{ value, label: titleCase(value) }],
        }];
      }

      return [];
    });
}

function selectedMissionItem(commandItem: TypedDraftItem | null): MissionItem | null {
  if (!commandItem) {
    return null;
  }

  return commandItem.document as MissionItem;
}

let missionItem = $derived(selectedMissionItem(item));
let position = $derived(missionItem ? commandPosition(missionItem.command) : null);
let selectedCommandVariant = $derived(missionItem ? commandVariant(missionItem.command) : null);
let selectedCommandValue = $derived(missionItem ? commandSelectValue(missionItem.command) : "");
let selectedCommandMetadata = $derived(missionItem ? commandMetadata(missionItem.command) : null);
let fields = $derived(missionItem ? editableFields(missionItem.command) : []);
let previousCoordinates = $derived.by(() => {
  if (!previousItem || previousItem.preview.latitude_deg === null || previousItem.preview.longitude_deg === null) {
    return null;
  }

  return `${previousItem.preview.latitude_deg.toFixed(5)}, ${previousItem.preview.longitude_deg.toFixed(5)}`;
});

function fieldInputId(fieldKey: string) {
  return `mission-inspector-${item?.uiId ?? "none"}-${fieldKey}`;
}

function fieldHelpId(fieldKey: string) {
  return `${missionWorkspaceTestIds.inspectorFieldHelpPrefix}-${fieldKey}`;
}

function fieldDescriptionId(fieldKey: string) {
  return `${fieldHelpId(fieldKey)}-description`;
}

function numericFieldValue(field: EditableField) {
  return typeof field.value === "number" ? field.value + (field.displayOffset ?? 0) : field.value;
}

function setFieldInfoOpen(fieldKey: string, open: boolean) {
  if (open) {
    expandedFieldKey = fieldKey;
    return;
  }

  if (expandedFieldKey === fieldKey) {
    expandedFieldKey = null;
  }
}

function inputValue(event: Event): string {
  return event.currentTarget instanceof HTMLInputElement ? event.currentTarget.value : "";
}

function selectValue(event: Event): string {
  return event.currentTarget instanceof HTMLSelectElement ? event.currentTarget.value : "";
}

function coordinateInputValue(value: number): number {
  return Number(value.toFixed(7));
}

function updateField(fieldKey: string, value: unknown) {
  if (!missionItem || !item || item.readOnly) {
    return;
  }

  onUpdateCommand(item.index, withCommandField(missionItem.command, fieldKey, value));
}

function updateNumberField(field: EditableField, rawValue: string) {
  if (rawValue.trim().length === 0) {
    return;
  }

  const nextValue = Number(rawValue);
  if (Number.isFinite(nextValue)) {
    updateField(field.key, nextValue - (field.displayOffset ?? 0));
  }
}

function updateLatitudeInput(event: Event) {
  if (!item) {
    return;
  }

  const rawValue = inputValue(event);
  if (rawValue.trim().length === 0) {
    return;
  }

  const nextValue = Number(rawValue);
  if (Number.isFinite(nextValue)) {
    onUpdateLatitude(item.index, nextValue);
  }
}

function updateLongitudeInput(event: Event) {
  if (!item) {
    return;
  }

  const rawValue = inputValue(event);
  if (rawValue.trim().length === 0) {
    return;
  }

  const nextValue = Number(rawValue);
  if (Number.isFinite(nextValue)) {
    onUpdateLongitude(item.index, nextValue);
  }
}

function updateAltitudeInput(event: Event) {
  if (!item) {
    return;
  }

  const rawValue = inputValue(event);
  if (rawValue.trim().length === 0) {
    return;
  }

  const nextValue = Number(rawValue);
  if (Number.isFinite(nextValue)) {
    onUpdateAltitude(item.index, nextValue);
  }
}
</script>

<Card.Root as="section" density="compact" testId={missionWorkspaceTestIds.inspector}>
  <div class="flex items-center gap-2">
    <Settings2 aria-hidden="true" class="shrink-0 text-accent" size={16} />
    <Eyebrow tracking="widest">Inspector</Eyebrow>

    <Badge case="normal" class="ml-auto" variant="muted" testId={missionWorkspaceTestIds.inspectorSelectionKind}>
      {selection.kind === "mission-item" && item ? `mission-item · #${item.index + 1}` : selection.kind}
    </Badge>
  </div>

  {#if selection.kind === "home"}
    <EmptyState
      class="mt-4"
      description="Edit the Home card to set mission origin data, or select a manual mission item or survey region to edit it inside the shared workspace."
      testId={missionWorkspaceTestIds.inspectorEmpty}
      title="Home is selected."
    />
    {#if home}
      <HelperText class="mt-2" size="xs">Current Home · {home.latitude_deg.toFixed(5)}, {home.longitude_deg.toFixed(5)} · {home.altitude_m.toFixed(1)} m</HelperText>
    {/if}
  {:else if selection.kind === "survey-block"}
    {#if selectedSurveyRegion}
      <MissionSurveyInspector
        cruiseSpeed={cruiseSpeed}
        onConfirmSurveyPrompt={onConfirmSurveyPrompt}
        onDeleteRegion={onDeleteSurveyRegion}
        onDismissSurveyPrompt={onDismissSurveyPrompt}
        onGenerateRegion={onGenerateSurveyRegion}
        onMarkGeneratedItemEdited={(regionId, localIndex, editedItem) => onMarkSurveyRegionItemAsEdited(regionId, localIndex, editedItem)}
        onPromptDissolveRegion={onPromptDissolveSurveyRegion}
        onUpdateRegion={(regionId, updater) => onUpdateSurveyRegion(regionId, updater)}
        region={selectedSurveyRegion}
        {surveyPrompt}
      />
    {:else}
      <Alert class="mt-4" density="compact" variant="warning" testId={missionWorkspaceTestIds.inspectorReadonly}>
        <p class="font-semibold">Survey selection unavailable</p>
        <p class="mt-2 text-xs text-warning/90">
          The selected survey region could not be resolved from the active planner state, so the inspector stayed fail-closed instead of rendering broken controls.
        </p>
      </Alert>
    {/if}
  {:else if !item || !missionItem}
    <EmptyState
      class="mt-4"
      testId={missionWorkspaceTestIds.inspectorEmpty}
      title="Select a manual mission item from the list."
      description="Coordinates and typed command fields appear here once a mission item is selected."
    />
  {:else}
    <div class="mt-4 space-y-3">
      {#if item.readOnly}
        <Alert density="compact" layout="stacked" variant="warning" testId={missionWorkspaceTestIds.inspectorReadonly}>
          <p class="font-semibold">Unsupported/raw mission item</p>
          <p class="mt-1 text-xs text-warning/90">This preserved command stays read-only. Its raw parameters remain visible so imported content is not flattened away.</p>
          <dl class="mt-3 grid gap-2 sm:grid-cols-2">
            {#each fields as field (field.key)}
              <FactTile density="compact" label={field.label} tone="warning" value={String(field.value)} unit={field.units} />
            {/each}
          </dl>
        </Alert>
      {:else}
        {#if selectedCommandVariant}
          <div class="space-y-1" data-testid={missionWorkspaceTestIds.inspectorCommandPicker}>
            <label class="text-[10px] font-medium text-text-muted" for="mission-command-select">Command</label>
            <MissionCommandPicker
              disabled={false}
              value={selectedCommandValue}
              onSelect={(category, variant) => {
                onUpdateCommand(item.index, defaultCommand(category, variant, position ?? undefined));
              }}
            />
            {#if previousCoordinates}
              <p class="text-[10px] text-text-muted">Previous manual item · {previousCoordinates}</p>
            {/if}
          </div>
        {/if}

        {#if selectedCommandMetadata}
          <Alert
            class="rounded-md text-[10px] leading-relaxed"
            density="compact"
            shadow={false}
            testId={missionWorkspaceTestIds.inspectorCommandHelp}
            variant="info"
          >
            <div class="flex items-start gap-1.5">
              <Info aria-hidden="true" class="mt-0.5 shrink-0 text-accent/70" size={12} />
              <span class="text-text-secondary">{selectedCommandMetadata.summary}</span>
            </div>

            {#if selectedCommandMetadata.notes?.length}
              <ul class="mt-1.5 space-y-1">
                {#each selectedCommandMetadata.notes as note, index (`${note}-${index}`)}
                  <li class="flex items-start gap-1.5">
                    <AlertTriangle aria-hidden="true" class="mt-0.5 shrink-0 text-warning/70" size={11} />
                    <span>{note}</span>
                  </li>
                {/each}
              </ul>
            {/if}

            {#if selectedCommandMetadata.docsUrl}
              <ExternalLink
                class="mt-1.5 text-[10px]"
                testId={missionWorkspaceTestIds.inspectorCommandDocs}
                href={selectedCommandMetadata.docsUrl}
              >
                ArduPilot Docs
              </ExternalLink>
            {/if}
          </Alert>
        {/if}

        {#if fields.length > 0}
          <div class="space-y-1.5">
            <p class="text-[10px] font-medium text-text-muted">Parameters</p>
            {#each fields as field (field.key)}
              <Field.Root class={`gap-1 ${field.supported === false ? "opacity-60" : ""}`}>
                <div class="flex items-center gap-1">
                  <Field.Label class="text-[10px] text-text-muted" for={fieldInputId(field.key)}>
                    {field.label}
                  </Field.Label>
                  {#if field.required}
                    <span aria-label="required" class="text-warning">*</span>
                    <span class="text-[9px] text-warning/80">required</span>
                  {/if}
                  {#if field.description}
                    <Tooltip
                      align="start"
                      clickToToggle
                      contentId={`${fieldHelpId(field.key)}-tooltip`}
                      contentTestId={fieldHelpId(field.key)}
                      description={field.description}
                      label={`${field.label} help`}
                      onOpenChange={(open) => setFieldInfoOpen(field.key, open)}
                      open={expandedFieldKey === field.key}
                      side="top"
                      title={field.label}
                    >
                      <IconButton
                        aria-controls={`${fieldHelpId(field.key)}-tooltip`}
                        aria-expanded={expandedFieldKey === field.key}
                        ariaLabel={`Show ${field.label} help`}
                        class="rounded-full p-0.5"
                        size="auto"
                        testId={`${missionWorkspaceTestIds.inspectorFieldInfoPrefix}-${field.key}`}
                        title=""
                        tone="accent"
                        variant="ghost"
                        type="button"
                      >
                        <Info aria-hidden="true" size={11} />
                      </IconButton>
                    </Tooltip>
                    <span class="sr-only" id={fieldDescriptionId(field.key)}>{field.description}</span>
                  {/if}
                </div>

                {#if field.supported === false && !field.description}
                  <p class="text-[10px] leading-relaxed text-warning/80">Not supported by ArduPilot for this command.</p>
                {/if}

                {#if field.type === "number"}
                  <NumberInput
                    aria-describedby={field.description ? fieldDescriptionId(field.key) : undefined}
                    class="tabular-nums"
                    disabled={field.supported === false}
                    id={fieldInputId(field.key)}
                    inputmode="decimal"
                    onchange={(event) => updateNumberField(field, inputValue(event))}
                    size="sm"
                    testId={`${missionWorkspaceTestIds.inspectorFieldPrefix}-${field.key}`}
                    unit={field.units}
                    value={Number(numericFieldValue(field))}
                  />
                {:else if field.type === "boolean"}
                  <Switch
                    aria-describedby={field.description ? fieldDescriptionId(field.key) : undefined}
                    checked={Boolean(field.value)}
                    disabled={field.supported === false}
                    id={fieldInputId(field.key)}
                    label={field.value ? "Enabled" : "Disabled"}
                    onCheckedChange={(checked) => updateField(field.key, checked)}
                    testId={`${missionWorkspaceTestIds.inspectorFieldPrefix}-${field.key}`}
                  />
                {:else}
                  <NativeSelect
                    aria-describedby={field.description ? fieldDescriptionId(field.key) : undefined}
                    disabled={field.supported === false}
                    id={fieldInputId(field.key)}
                    onchange={(event) => updateField(field.key, selectValue(event))}
                    options={field.enumOptions ?? []}
                    size="sm"
                    testId={`${missionWorkspaceTestIds.inspectorFieldPrefix}-${field.key}`}
                    value={String(field.value)}
                  />
                {/if}
              </Field.Root>
            {/each}
          </div>
        {/if}

        {#if position}
          <div class="space-y-2 border-t border-border/60 pt-3">
            <div class="flex items-center justify-between gap-2">
              <p class="text-[10px] font-medium text-text-muted">Coordinates</p>
              <span class="text-[10px] text-text-muted">Relative Alt</span>
            </div>
            <div class="grid gap-2 sm:grid-cols-2">
              <Field.Root class="gap-1">
                <Field.Label class="text-[10px] text-text-muted">Latitude (deg)</Field.Label>
                  <NumberInput
                    class="tabular-nums"
                    inputmode="decimal"
                    onchange={updateLatitudeInput}
                    size="sm"
                    testId={missionWorkspaceTestIds.inspectorLatitude}
                    value={coordinateInputValue(geoPoint3dLatLon(position).latitude_deg)}
                  />
              </Field.Root>

              <Field.Root class="gap-1">
                <Field.Label class="text-[10px] text-text-muted">Longitude (deg)</Field.Label>
                  <NumberInput
                    class="tabular-nums"
                    inputmode="decimal"
                    onchange={updateLongitudeInput}
                    size="sm"
                    testId={missionWorkspaceTestIds.inspectorLongitude}
                    value={coordinateInputValue(geoPoint3dLatLon(position).longitude_deg)}
                  />
              </Field.Root>
            </div>

            <Field.Root class="gap-1">
              <Field.Label class="text-[10px] text-text-muted">Altitude (m)</Field.Label>
              <NumberInput
                class="tabular-nums"
                inputmode="decimal"
                onchange={updateAltitudeInput}
                size="sm"
                testId={missionWorkspaceTestIds.inspectorAltitude}
                value={item.preview.altitude_m ?? 0}
              />
            </Field.Root>
          </div>
        {:else}
          <EmptyState
            title="No coordinate fields for this command."
            description="Switching between commands updates the inspector fields truthfully instead of leaving stale coordinate inputs mounted."
          />
        {/if}
      {/if}
    </div>
  {/if}
</Card.Root>
